/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:2875b77f-6116-424b-b654-49be2f4e721f",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_eIJ2Bf2F1",
    "aws_user_pools_web_client_id": "qq0450u1fqh7pc5n778aqhnl0",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://sqroudm7sbbuja3i3jbshl3w2u.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3py7zi5tpfh7rdx4ur5fjtb6gq"
};


export default awsmobile;
